export const PHRASES = [
  "Embrace the chaos, find your star.",
  "You are the universe expressing itself.",
  "Every atom in you came from a star.",
  "Silence is the language of the cosmos.",
  "Your potential is infinite like space.",
  "Shine bright, even in the dark.",
  "Gravity cannot hold your dreams.",
  "Orbit your own happiness.",
  "Dust and dreams make galaxies.",
  "The universe dances with you.",
  "Be a planet of peace.",
  "Rings of light surround you.",
  "Expand your horizons.",
  "Nebulas are born from collapse.",
  "You are made of stardust.",
  "Drift into the serene void.",
  "Observe the beauty of time.",
  "Let your light travel far.",
  "Connect with the infinite.",
  "Space to breathe, space to be.",
  "A galaxy in every thought.",
  "Keep your orbit steady.",
  "The sky is not the limit.",
  "Explore the inner universe.",
  "Radiate positive energy.",
  "Cosmic winds guide you.",
  "Stars don't compete, they just shine.",
  "Find balance in the vacuum.",
  "Create your own constellation.",
  "Saturn teaches us patience.",
  "Beauty lies in the rings.",
  "Listen to the cosmic hum.",
  "Float above the noise.",
  "Your soul is a supernova.",
  "Time is a relative friend.",
  "Energy never dies.",
  "Flow like a comet.",
  "Illuminate the unknown.",
  "Mystery is the heart of wonder.",
  "The void is full of potential.",
  "Spin with grace.",
  "Attract what you desire.",
  "You are a celestial body.",
  "Light travels, so should you.",
  "Darkness defines the light.",
  "Revolve around love.",
  "Harmony of the spheres.",
  "See the world from above.",
  "Distance brings perspective.",
  "Interstellar dreams await.",
  "Launch your ideas.",
  "Gravity is just a suggestion.",
  "Eclipses are temporary.",
  "Shine for yourself.",
  "A universe of possibilities.",
  "Starlight is ancient wisdom.",
  "Be vast, be brilliant.",
  "Navigate by your own stars.",
  "Cosmos in a grain of sand.",
  "Everything is connected.",
  "Breathe in the nebula.",
  "Exhale the meteor dust.",
  "Silence is loud in space.",
  "Colors of the cosmos.",
  "A spiral of creativity.",
  "Infinite loops of joy.",
  "Meteor showers of luck.",
  "Planetary alignment is now.",
  "Touch the event horizon.",
  "Escape velocity achieved.",
  "Zero gravity, zero worries.",
  "Moonlight guides the lost.",
  "Sunlight warms the soul.",
  "The rings protect the core.",
  "A journey of light years.",
  "Transcend the atmosphere.",
  "Orbiting new ideas.",
  "Galactic peace of mind.",
  "Stellar evolution is you.",
  "The big bang is still happening.",
  "Echoes of the ancient past.",
  "Future is unwritten space.",
  "Watch the planets align.",
  "Feel the pull of destiny.",
  "Rotate towards the sun.",
  "Phases of the moon, phases of life.",
  "A comet's tail of hope.",
  "Asteroids of challenge pass by.",
  "The vacuum is not empty.",
  "Dark matter holds us together.",
  "Singularity of self.",
  "Wormholes to happiness.",
  "Quasars of energy.",
  "Pulsars of rhythm.",
  "Red giants and white dwarfs.",
  "Supermassive love.",
  "The final frontier is within.",
  "Look up and wonder.",
  "You are exactly where you need to be.",
  "The universe has your back."
];

// 3D Visual Constants
export const PARTICLE_COUNT = 8000;
export const SATURN_RADIUS = 15;
export const RING_INNER_RADIUS = 20;
export const RING_OUTER_RADIUS = 40;
export const EXPANSION_SCALE = 50; // How far they spread
export const CAMERA_CHECK_INTERVAL_MS = 600; // Check gesture every 600ms